In [1]:
import numpy as np

In [9]:
a = np.arange(4).reshape(4, -1)
a, a.shape

(array([[0],
        [1],
        [2],
        [3]]), (4, 1))

In [10]:
b = (np.arange(2) + 1).reshape(1, -1)
b, b.shape

(array([[1, 2]]), (1, 2))

In [11]:
a.dot(b)

array([[0, 0],
       [1, 2],
       [2, 4],
       [3, 6]])